### ISSUE TITLE
Is it possible to publish the version of the script

### ISSUE THREAD

**Issue by dnknn** [addshore/browser-github-release-downloads#10]
Thank you very much for this extension.
Can it have Tampermonkey's script also?
A single extension, it feels like occupying the browser's toolbar.

**Comment by addshore** [comment]
Well, the whole script is in https://github.com/addshore/browser-github-release-downloads/blob/master/app/scripts/contentscript.js

You should be able to make that work?

> A single extension, it feels like occupying the browser's toolbar.

At least in the current version of Chrome, you can choose to not display the icons of extensions in the toolbar

![image](https://user-images.githubusercontent.com/3308769/86225895-c5fc2480-bb82-11ea-99f0-13391c7d0e21.png)

**Comment by dnknn** [comment]
Is it directly pasted in Tampermonkey?
Can make one as UserScript format?, i don’t understand the metadata of the script.

**Comment by addshore** [comment]
Aaah yes you'll also need to load a css file https://github.com/addshore/browser-github-release-downloads/blob/master/app/styles/style.css
Once you do that it should work.

> Can make one as UserScript format?, i don’t understand the metadata of the script.

I don't know how to do that and don't really have the time to figure it out right now, but it looks like you are close!

It's possible that I might be able to add a tampermonkey script to some build step in the future, but that will have to wait for the future.

**Comment by dnknn** [comment]
Thanks

**Comment by Vangelis66** [comment]
@dknm asked:

> Can it have **Tampermonkey**'s script also?
> ...
> Can make one as **UserScript** format?, I don’t understand the metadata of the script.

@addshore replied: 

> I don't know how to do that and don't really have the time to figure it out right now, 
> but it looks like you are close!
> 
> It's possible that I might be able to add a tampermonkey script to some build step in the future, 
> but that will have to wait for the future.

... I know I'm late 😉 , still... 

I'm using a **Mozilla Firefox** fork called **Serpent 52.9.0**, initially sourced from **FirefoxESR 52.9.0**, which is quite popular now among users of _older_ Windows OSes (like XP/Vista/7); the version of this extension hosted on [AMO](https://addons.mozilla.org/en-US/firefox/addon/github-release-download-count/), while it **does install** on Serpent 52.9.0, doesn't work as advertised, possibly because AMO **never tested** the correct functioning of the extension on that old a Firefox version (yet they label it as **Fx48+** compatible... 😠 ).

![AMO](https://user-images.githubusercontent.com/9669492/139759455-5163a391-c5c9-4b3e-8d15-91c2c0647654.JPG)

Because I **still wanted** the functionality offered by the extension on **St52**, I set out to convert the latest working version, `1.3.3`, to a **userscript**, that could be installed in my preferred **UserScript Manager**, the open-source [Violentmonkey](https://github.com/violentmonkey/violentmonkey)...

My **Javascript**+**CSS** skills are pretty much non-existent 😄 , however, as pointed out already in this issue, the basic idea is to create a UserScript that uses both 
https://raw.githubusercontent.com/addshore/browser-github-release-downloads/master/app/styles/style.css
and 
https://raw.githubusercontent.com/addshore/browser-github-release-downloads/master/app/scripts/contentscript.js

**On-line articles** were a big help to that end :+1:, so, after a few hours of trial-and-error, my goal was achieved! 🎉 

In the end, I created **two variants** of the userscript; the first one **embeds the CSS**, while the second one **retrieves it (from GitHub) as a `@resource`**; **all credit** for the **CSS** and **JS** code goes to @addshore, all **I** did was sew them together into a working userscript (and that should be all I should be credited for 😃 ).
Userscripts code follows;
v1:

```JS
// ==UserScript==
// @name        GitHub Release Downloads Count v1
// @version     1.3.3_1
// @description Userscript that displays GitHub Release download counters; it just shows the downloads count near each release in GitHub.
// @license     MIT
// @author      addshore
// @namespace   https://github.com/addshore
// @include     https://github.com/*
// @run-at      document-start
// @grant       GM_addStyle
// @icon        https://github.com/addshore/browser-github-release-downloads/raw/master/app/images/icon48.png
// @supportURL  https://github.com/addshore/browser-github-release-downloads/issues
// ==/UserScript==

"use strict";

GM_addStyle (`
  details div.Box div.Box-body small {
    text-align: right;
  }
  .githubdownloadscounter {
    padding-right: 0.69em;
  }
  .githubdownloadscounter span {
    display: block;
    width: 13px;
    height: 17px;
    float: right;
    background-size: 10px;
    background-repeat: no-repeat;
    background-position: center right;
    background-image: url("data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMyIgaGVpZ2h0PSIyNyIgdmlld0JveD0iMCAwIDIzIDI3Ij48ZGVmcz48cGF0aCBkPSJNMjEuOSAxNUMyMS45IDE1IDEzLjIgMjQuOSAxMi40IDI2IDExLjUgMjcuMSAxMC4xIDI2LjMgMTAuMSAyNi4zIDEwLjEgMjYuMyAxLjMgMTYuNiAwLjMgMTQuOSAtMC43IDEzLjMgMS4yIDEzIDEuMiAxM0w2IDEzIDYgMUM2IDAuNCA2LjQgMCA3IDBMMTUgMEMxNS42IDAgMTYgMC40IDE2IDFMMTYgMTMgMjAuNyAxM0MyMy4xIDEzIDIxLjkgMTUgMjEuOSAxNVoiLz48L2RlZnM+PGcgZmlsbD0iIzU4NjA2OSI+PHBhdGggZD0iTTIxLjEgMTQuNEMyMS4xIDE0LjQgMjEuMSAxNC40IDIxLjEgMTQuMyAyMS4yIDE0LjIgMjEuMiAxNC4xIDIxLjIgMTQuMSAyMS4xIDE0IDIxIDE0IDIwLjcgMTRMMTUgMTQgMTUgMSA3IDEgNyAxNCAxLjMgMTRDMS4yIDE0IDEuMSAxNCAxLjEgMTQuMSAwLjkgMTQuMiAxIDE0LjEgMS4yIDE0LjQgMS41IDE1IDMuMiAxNyA1LjcgMTkuOCA1LjggMjAgNS44IDIwIDUuOSAyMC4xIDcgMjEuMyA4LjEgMjIuNiA5LjMgMjMuOSA5LjcgMjQuNCAxMC4xIDI0LjggMTAuNCAyNS4yIDEwLjUgMjUuMyAxMC42IDI1LjQgMTAuNyAyNS41IDEwLjcgMjUuNSAxMC43IDI1LjUgMTAuOCAyNS41IDExIDI1LjYgMTEuMiAyNS42IDExLjQgMjUuNiAxMS41IDI1LjUgMTEuNSAyNS41IDExLjYgMjUuNCAxMiAyNC45IDEzLjYgMjMgMTYuMyAxOS45IDE2LjMgMTkuOSAxNi4zIDE5LjkgMTYuNCAxOS44IDE3LjQgMTguNiAxOC41IDE3LjMgMTkuNyAxNiAyMCAxNS42IDIwLjQgMTUuMiAyMC43IDE0LjggMjAuOSAxNC42IDIxIDE0LjUgMjEuMSAxNC40WiIgc3R5bGU9InN0cm9rZS13aWR0aDoyO3N0cm9rZTojNTg2MDY5Ii8+PC9nPjwvc3ZnPg==");
  }
`);

var xmlHttp = new XMLHttpRequest();
xmlHttp.onreadystatechange = function () {
  switch (xmlHttp.readyState) {
    case 0: // UNINITIALIZED
    case 1: // LOADING
    case 2: // LOADED
    case 3:
      // INTERACTIVE
      break;
    case 4:
      // COMPLETED
      var releases = JSON.parse(xmlHttp.responseText);
      var downloadMap = [];
      for (var i in releases) {
        for (var j in releases[i].assets) {
          // browser_download_url is a full URL to the resource
          downloadMap[decodeURI(releases[i].assets[j].browser_download_url)] = releases[i].assets[j].download_count;
        }
      }
      var els = document.getElementsByTagName("a");
      //var locale = getLocale();
      for (var i = 0, l = els.length; i < l; i++) {
        var el = els[i];
        if (el.href in downloadMap) {
          var dwnCount = document.createElement("small");
          dwnCount.className = "githubdownloadscounter text-gray float-right"; // Right style
          var d = downloadMap[el.href];
          //if (locale.length) {
          //  d = d.toLocaleString("en-US");
          //}
          dwnCount.appendChild(document.createTextNode(d));
          var dwnIcon = document.createElement("span");
          dwnCount.appendChild(dwnIcon);
          var sizes = el.parentNode.querySelectorAll("[data-test-selector=asset-size-label]");
          if (!sizes) {
            console.log("No size elements found to attached download count to");
            continue;
          }
          var size = sizes[0];
          if (!size) {
            console.log("No size element selectable to attached download count to");
            continue;
          }
          el.parentNode.insertBefore(dwnCount, size);
          dwnCount.style.minWidth = dwnCount.offsetWidth + 3 + "px";
          dwnCount.style.flexGrow = "2";
          dwnCount.style.marginLeft = "5px";
        }
      }
      break;
    default:
      console.log("Error: GitHub Release Download Count Request Errored.");
  }
};
xmlHttp.open("GET", document.URL.replace("//github.com", "//api.github.com/repos").split("/tag/")[0], true);
xmlHttp.send(null);
```
v2:

```JS
// ==UserScript==
// @name        GitHub Release Downloads Count v2
// @version     1.3.3_2
// @description Userscript that displays GitHub Release download counters; it just shows the downloads count near each release in GitHub.
// @license     MIT
// @author      addshore
// @namespace   https://github.com/addshore
// @include     https://github.com/*
// @run-at      document-start
// @resource    IMPORTED_CSS https://raw.githubusercontent.com/addshore/browser-github-release-downloads/master/app/styles/style.css
// @grant       GM_getResourceText
// @grant       GM_addStyle
// @icon        https://github.com/addshore/browser-github-release-downloads/raw/master/app/images/icon48.png
// @supportURL  https://github.com/addshore/browser-github-release-downloads/issues
// ==/UserScript==

"use strict";

var cssTxt = GM_getResourceText("IMPORTED_CSS");
  GM_addStyle (cssTxt);

var xmlHttp = new XMLHttpRequest();
xmlHttp.onreadystatechange = function () {  
  switch (xmlHttp.readyState) {
    case 0: // UNINITIALIZED
    case 1: // LOADING
    case 2: // LOADED
    case 3:
      // INTERACTIVE
      break;
    case 4:
      // COMPLETED
      var releases = JSON.parse(xmlHttp.responseText);
      var downloadMap = [];
      for (var i in releases) {
        for (var j in releases[i].assets) {
          // browser_download_url is a full URL to the resource
          downloadMap[decodeURI(releases[i].assets[j].browser_download_url)] = releases[i].assets[j].download_count;
        }
      }
      var els = document.getElementsByTagName("a");
      //var locale = getLocale();
      for (var i = 0, l = els.length; i < l; i++) {
        var el = els[i];
        if (el.href in downloadMap) {
          var dwnCount = document.createElement("small");
          dwnCount.className = "githubdownloadscounter text-gray float-right"; // Right style
          var d = downloadMap[el.href];
          //if (locale.length) {
          //  d = d.toLocaleString("en-US");
          //}
          dwnCount.appendChild(document.createTextNode(d));
          var dwnIcon = document.createElement("span");
          dwnCount.appendChild(dwnIcon);
          var sizes = el.parentNode.querySelectorAll("[data-test-selector=asset-size-label]");
          if (!sizes) {
            console.log("No size elements found to attached download count to");
            continue;
          }
          var size = sizes[0];
          if (!size) {
            console.log("No size element selectable to attached download count to");
            continue;
          }
          el.parentNode.insertBefore(dwnCount, size);
          dwnCount.style.minWidth = dwnCount.offsetWidth + 3 + "px";
          dwnCount.style.flexGrow = "2";
          dwnCount.style.marginLeft = "5px";
        }
      }
      break;
    default:
      console.log("Error: GitHub Release Download Count Request Errored.");
  }
};
xmlHttp.open("GET", document.URL.replace("//github.com", "//api.github.com/repos").split("/tag/")[0], true);
xmlHttp.send(null);
```
Userscripts installed in latest **Violentmonkey 2.13.0.10 (beta)**: 

![VM](https://user-images.githubusercontent.com/9669492/139769668-502e7960-31d9-4cae-b154-898f4c0de25f.JPG)

One obvious caveat is the **lack of update support**, i.e. I'll have to manually modify the userscript whenever the extension itself gets updated (and, fingers-crossed, it'll be a long while until _that_ happens again - read: GitHub mess with the Releases UI 👎 ) ...

**Comment by addshore** [comment]
Awesome!
I wonder if we could turn building this user script into part of the build here.
I'll have a look when I next look at this repo.

And yeah, hopefully it'll be another year before this needs an update :)
