### ISSUE TITLE
GitHub releases changed?

### ISSUE THREAD

**Issue by DmitriySalnikov** [addshore/browser-github-release-downloads#34]
I just downloaded this extension and no downloads information is visible.

**Comment by aonez** [comment]
Indeed it seems.

**Comment by aonez** [comment]
This pull should fix this: https://github.com/addshore/browser-github-release-downloads/pull/35

**Comment by addshore** [comment]
Resolved in the next version which is pending approval on the browser stores

**Comment by 54m4d** [comment]
@addshore i just downloaded the extension but i cannot see any number of downloads on the releases pages, is it still working?

**Comment by addshore** [comment]
I also just saw a review that said the same thing.
I suspect GitHub changed something in their UI again, and the extension needs updating.
I'll try and take a look soon (unless someone beats me)

**Comment by addshore** [comment]
In the currently released version (1.3.4) in chrome I get something like this
![image](https://user-images.githubusercontent.com/3308769/225614059-2aff2572-6de6-43a1-99ba-e53635785745.png)
Not ideal, but it is there!

**Comment by addshore** [comment]
@54m4d Could you open a new issue on this repo, provide a screenshot, note which version you are using and what browser?
A link the the repo you are trying to see the download counts for would be great too!

**Comment by aonez** [comment]
For what is worth, on my Safari end is like a hit or miss, sometimes appears and sometimes it doesn't. Usually refreshing the page or reenabling the extension fixes it.

Did not had the time to investigate more.

**Comment by 54m4d** [comment]
For some strange reason it's working now, (CRM latest version) i have no idea what the issue could have been.

**Comment by addshore** [comment]
If it happens again, take a look in the dev console to see if there are any extension related errors, particuarly to do with the API call to github that is made to retrieve the download counts!

**Comment by 54m4d** [comment]
OK
